package consts

var BankCodes = map[string]string{
	"1":   "Türkiye Cumhuriyet Merkez Bankası A.Ş.",
	"4":   "İller Bankası",
	"10":  "Türkiye Cumhuriyeti Ziraat Bankası A.Ş.",
	"12":  "Türkiye Halk Bankası A.Ş.",
	"13":  "Denizbank",
	"14":  "Türkiye Sınai Kalkınma Bankası A.Ş.",
	"15":  "Türkiye Vakıflar Bankası T.A.O.",
	"16":  "Türkiye İhracat Kredi Bankası A.Ş. (Eximbank)",
	"17":  "Türkiye Kalkınma Bankası A.Ş.",
	"29":  "Birleşik Fon Bankası A.Ş. (Bayındırbank A.Ş.)",
	"32":  "Türk Ekonomi Bankası A.Ş.",
	"34":  "Aktif Yatırım Bankası A.Ş.",
	"46":  "Akbank T.A.Ş.",
	"48":  "HSBC Bank A.Ş.",
	"58":  "Sınai Yatırım Bankası A.Ş.",
	"59":  "Şekerbank T.A.Ş.",
	"62":  "Türkiye Garanti Bankası A.Ş.",
	"64":  "Türkiye İş Bankası A.Ş.",
	"67":  "Yapı ve Kredi Bankası A.Ş.",
	"71":  "Fortis Bank (TEB)",
	"87":  "Banca di Roma",
	"88":  "The Royal Bank of Scotland PLC Merkezi Amsterdam İstanbul Merkez Şubesi",
	"91":  "Arap Türk Bankası A.Ş.",
	"92":  "Citibank N.A.",
	"94":  "Bank Mellat",
	"95":  "BCCI",
	"96":  "Turkish Bank A.Ş.",
	"97":  "Habib Bank Limited",
	"98":  "JP Morgan Chase Bank İstanbul Türkiye Şubesi",
	"99":  "Oyak Bank A.Ş. - ING BANK",
	"100": "Adabank A.Ş.",
	"101": "Türk Sakura Bank A.Ş.",
	"103": "Fiba Bank A.Ş.",
	"104": "IMPEXBANK",
	"106": "PORTIGON A.G.",
	"107": "BNP-Ak-Dresdner Bank A.Ş.",
	"108": "Turkland Bank A.Ş.",
	"109": "Tekstil Bankası A.Ş.",
	"110": "Credit Lyonnais",
	"111": "Finansbank A.Ş.",
	"113": "Marbank",
	"115": "Deutsche Bank A.Ş.",
	"116": "TAİB Yatırım Bank A.Ş.",
	"117": "Turizm Yatırım ve Ticaret Bank A.Ş.",
	"118": "Kıbrıs Kredi Bankası",
	"119": "Birleşik Yatırım",
	"121": "Standard Chartered Yatırım Bankası Türk A.Ş.",
	"122": "Societe Generale",
	"123": "HSBC Bank A.Ş.",
	"124": "Alternatifbank A.Ş.",
	"125": "Burganbank A.Ş.",
	"127": "KentBank",
	"128": "Park Yatırım Bankası",
	"129": "Tat Yatırım Bankası A.Ş.",
	"132": "IMKB Takas ve Saklama Bankası A.Ş.",
	"133": "ING BANK",
	"134": "Denizbank A.Ş.",
	"135": "Anadolubank A.Ş.",
	"136": "Okan Yatırım Bankası A Ş",
	"137": "Rabobank Nederland İstanbul Merkez Şubesi",
	"138": "Diler Yatırım Bankası A.Ş.",
	"139": "GSD Yatırım Bankası A.Ş.",
	"140": "Credit Suisse First Boston İstanbul Şubesi",
	"141": "Nurol Yatırım Bankası A.Ş.",
	"142": "Bank Pozitif Kredi ve Kalkınma Bankası A.Ş.",
	"143": "Aktif Yatırım Bankası A.Ş.",
	"144": "Atlas Yatırım Bankası A.Ş.",
	"145": "Morgan Guarenty Trusy Company",
	"146": "OdeaBank A.Ş.",
	"147": "Bank of Tokyo -Mitsubishi UFJ Turkey A.Ş.",
	"148": "Intesa SanPaolo SPA İtalya-İstanbul Merkez Şubesi",
	"203": "Al Baraka Türk Katılım Bankası A.Ş.",
	"204": "Family Finans Kurumu",
	"205": "Kuveyt Türk Katılım Bankası A.Ş.",
	"206": "Türkiye Finans Katılım Bankası A.Ş.",
	"208": "Asya Katılım Bankası A.Ş.",
	"210": "Vakıf Katılım Bankası A.Ş.",
	"223": "Al Baraka Türk Katılım Bankası A.Ş.",
}

var PaymentCodes = map[string]string{
	"825": "Birleşik Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"826": "Cemete Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"827": "Turk Elektronik Para A.Ş.",
	"828": "Belbim Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"829": "Papara Elektronik Para A.Ş.",
	"830": "D Ödeme Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"831": "Nomu Pay Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"832": "İninal Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"833": "Payporter Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"834": "Paladyum Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"835": "Vodafone Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"836": "Aköde Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"837": "Erpa Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"838": "Sipay Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"839": "Ozan Elektronik Para A.Ş.",
	"840": "Token Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"842": "Moneypay Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"843": "TTM Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"845": "Vepara Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"846": "Parolapara Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"847": "Parakolay Elektronik Para A.Ş.",
	"848": "DSM Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"849": "Payco Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"850": "BPN Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"852": "N Kolay Ödeme ve Elektronik Para Kuruluşu A.Ş.",
	"853": "UPT Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"854": "Vizyon Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"857": "Moka Ödeme ve Elektronik Para Kuruluşu A.Ş.",
	"860": "Pratik İşlem Ödeme ve Elektronik Para A.Ş.",
	"861": "Faturamatik Elektronik Para ve Ödeme Kuruluşu A.Ş.",
	"863": "Paytr Ödeme ve Elektronik Para Kuruluşu A.Ş.",
	"864": "İyzi Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"869": "Turkcell Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"870": "TT Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"878": "Paratim Ödeme ve Elektronik Para Kuruluşu A.Ş.",
	"883": "İstanbul Ödeme ve Elektronik Para A.Ş.",
	"890": "Lydians Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"891": "Fastpay Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"892": "Paybull Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"893": "Dgpara Ödeme ve Elektronik Para Kuruluşu A.Ş.",
	"894": "Ahlatcı Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"896": "Fzypay Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"897": "ParaQR Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"899": "Rubik Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"911": "As Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"912": "Tom Pay Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"913": "A Ödeme ve Elektronik Para Hizmetleri A.Ş.",
	"914": "Papel Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"915": "Turkonay Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"916": "Paypole Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"917": "Moneyout Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"920": "Dinamik Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"921": "Vakıf Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"922": "Ziraat Finansal Teknolojiler Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"923": "Yemekpay Elektronik Para ve Ödeme Hizmetleri A.Ş.",
	"924": "Platform Ödeme Hizmetleri ve Elektronik Para A.Ş.",
	"925": "Garanti Ödeme ve Elektronik Para Hizmetleri A.Ş.",
}
